name: Terraform EKS Deployment

on:
  workflow_dispatch:

jobs:
  Terraform-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cached Packages
        uses: actions/cache@v3
        with:
          path: /usr/local/bin
          key: dependencies-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            dependencies-${{ runner.os }}-

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Terraform
        run: |
          cd terraform-eks-cluster
          terraform init

      - name: Validate Terraform Configuration
        run: |
          cd terraform-eks-cluster
          terraform validate

      - name: Plan Terraform Deployment
        run: |
          cd terraform-eks-cluster
          terraform plan 

      # - name: Apply Terraform Changes
      #   run: |
      #     cd terraform-eks-cluster
      #     terraform apply -auto-approve 
