name: Setup Apigee Hybrid Dependencies

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          sudo apt update && sudo apt install -y \
            git \
            curl \
            telnet \
            python3 \
            python3-pip

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: latest
