name: Setup Apigee Hybrid Dependencies

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          sudo apt update && sudo apt install -y \
            git \
            curl \
            telnet \
            python3 \
            python3-pip

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Install Google Cloud CLI
        run: |
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-$(curl -s https://dl.google.com/dl/cloudsdk/channels/rapid/components-2.json | jq -r '.version').tar.gz
          tar -xf google-cloud-sdk-*.tar.gz
          ./google-cloud-sdk/install.sh --quiet
          echo "source ~/google-cloud-sdk/path.bash.inc" >> ~/.bashrc
          source ~/.bashrc
          gcloud --version

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          sudo systemctl enable docker
          sudo systemctl start docker
          docker --version

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Install eksctl
        run: |
          curl -sL "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz
          sudo mv eksctl /usr/local/bin/
          eksctl version

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt update && sudo apt install -y terraform
          terraform --version

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible
          ansible --version
