name: Setup Apigee Hybrid Dependencies

on:
 workflow_dispatch:


jobs:
  Install-Pre-requisite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          sudo apt update && sudo apt install -y \
            git \
            curl \
            telnet \
            python3 \
            python3-pip

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Install eksctl
        run: |
          curl -sL "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz
          sudo mv eksctl /usr/local/bin/

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.16.2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Install Ansible
        run: |
          python3 -m pip install --user ansible






