name: Push Apigee Images to GCP Artifact Registry

on:
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write  # Needed for OIDC authentication
  content: read

jobs:
  push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP using OIDC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID'
          service_account: 'SERVICE_ACCOUNT_EMAIL'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify gcloud and Docker
        run: |
          gcloud --version
          docker --version

      - name: Make the script executable
        run: chmod +x scripts/push-apigee-images.sh

      - name: Run push script
        run: ./scripts/push-apigee-images.sh asia-south1-docker.pkg.dev/123456789/apigee-hybrid-images
