name: Check Installed Versions

on:
  workflow_dispatch:

jobs:
  Pre-requisite-Version-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cached Packages
        uses: actions/cache@v3
        with:
          path: /usr/local/bin
          key: dependencies-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            dependencies-${{ runner.os }}-
            
      - name: Verify Installed Versions
        run: |
          echo "Git Version: $(git --version)"
          echo ""

          echo "Docker Version: $(docker --version)"
          echo ""

          echo "Google Cloud SDK Version: $(gcloud --version)"
          echo ""

          echo "AWS CLI Version: $(aws --version)"
          echo ""

          echo "kubectl Version: $(kubectl version --client=true --output=json | jq -r '.clientVersion.gitVersion')"
          echo ""

          echo "eksctl Version: $(eksctl version)"
          echo ""

          echo "Helm Version: $(helm version --short)"
          echo ""

          echo "Terraform Version: $(terraform version | head -n1)"
          echo ""

          echo "Ansible Version: $(ansible --version | head -n1)"
          echo ""

          echo "Telnet Installed: $(command -v telnet >/dev/null 2>&1 && echo 'Yes' || echo 'No')"
          echo ""

          echo "Python3 Version: $(python3 --version)"
